# -*- coding: utf-8 -*-
"""CT Scan Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13V7kTTYVDRjjpwAOiUY7RxNQZRwb4qJ-

STEP 1: CT SCAN IMAGES UPLOAD
"""

!pip install ultralytics

import os
import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO
import random
import matplotlib.image as mpimg
import tensorflow as tf

import zipfile
import os

# Replace 'baggage_dataset.zip' with your uploaded file name
with zipfile.ZipFile("/content/Threat_detection.zip", 'r') as zip_ref:
    zip_ref.extractall("dataset")  # extracts into a folder named "dataset"

# Check structure
os.listdir("dataset")

"""DATA PREPROCESSING"""

# Step 3: List folders
dataset_path = "dataset"
folders = os.listdir(dataset_path)
print("Folders:", folders)

# Step 4: Show 3 sample images from each folder
for folder in folders:
    folder_path = os.path.join(dataset_path, folder)
    images = os.listdir(folder_path)

    # Pick 3 random images
    sample_images = random.sample(images, min(3, len(images)))

    plt.figure(figsize=(10,3))
    plt.suptitle(f"Sample images from {folder}", fontsize=14)

    for i, img_name in enumerate(sample_images):
        img_path = os.path.join(folder_path, img_name)
        img = mpimg.imread(img_path)

        plt.subplot(1, 3, i+1)
        plt.imshow(img)
        plt.axis('off')
        plt.title(img_name.split('.')[0])

    plt.show()

"""CHECK DATASET INFORMATION"""

# Count images in each folder
dataset_path = "dataset"
folders = os.listdir(dataset_path)

for folder in folders:
    folder_path = os.path.join(dataset_path, folder)
    num_images = len(os.listdir(folder_path))

    print(f"{folder} : {num_images} images")

"""TRAINING - 80%"""

# Dataset path
dataset_path = "dataset"

# Load dataset
train_dataset = tf.keras.preprocessing.image_dataset_from_directory(
    dataset_path,
    image_size=(224, 224),   # resize images
    batch_size=32,
    validation_split=0.2,
    subset="training",
    seed=42
)

"""VALIDATION - 20%"""

validation_dataset = tf.keras.preprocessing.image_dataset_from_directory(
    dataset_path,
    image_size=(224, 224),
    batch_size=32,
    validation_split=0.2,
    subset="validation",
    seed=42
)

"""NORMALIZATION"""

# Normalize training and validation datasets
normalization_layer = tf.keras.layers.Rescaling(1./255)

train_dataset = train_dataset.map(lambda x, y: (normalization_layer(x), y))
validation_dataset = validation_dataset.map(lambda x, y: (normalization_layer(x), y))

"""DATA AUGMENTATION"""

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.1),
    tf.keras.layers.RandomZoom(0.1),
])

# Apply to training dataset
train_dataset = train_dataset.map(lambda x, y: (data_augmentation(x, training=True), y))

train_dataset = train_dataset.prefetch(buffer_size=tf.data.AUTOTUNE)
validation_dataset = validation_dataset.prefetch(buffer_size=tf.data.AUTOTUNE)

"""TRAINING THE DATA"""

dataset_path = "dataset/images"

for root, dirs, files in os.walk(dataset_path):
    level = root.replace(dataset_path, "").count(os.sep)
    indent = " " * 4 * level
    print(f"{indent}{os.path.basename(root)}/")
    for f in files[:5]:  # show only first 5 images per folder
        print(f"{indent}    {f}")

"""YOLOv8"""

# Load pretrained YOLOv8 small model
model = YOLO('yolov8n.pt')

model = YOLO("yolov8n-cls.pt")   # classification model

model.train(
    data="dataset",        # IMPORTANT: point to dataset root
    epochs=20,
    imgsz=224,
    batch=16,
    name="baggage_classification"
)

"""TEST"""

model.predict("/content/dataset_split/val/ThreatsRGB", show=True)

"""MODEL EVALUATION"""

results = model.predict("/content/dataset_split/val/ThreatsRGB")

print("Predicted class:", results[0].names[results[0].probs.top1])
print("Confidence:", results[0].probs.top1conf)

"""CONVERTED IMAGES TO .JPG"""

from PIL import Image
import os
import shutil

# Base folder containing your split folders
base_folder = "/content/dataset_split"

# Iterate through splits and class folders
for split in ["train", "val", "test"]:
    split_path = os.path.join(base_folder, split)
    if not os.path.exists(split_path):
        continue

    for class_folder in os.listdir(split_path):
        class_path = os.path.join(split_path, class_folder)
        if not os.path.isdir(class_path):
            continue

        # Create a new folder for converted images
        converted_folder = class_path + "_jpg"
        os.makedirs(converted_folder, exist_ok=True)

        for file in os.listdir(class_path):
            if file.lower().endswith(".tif"):
                img_path = os.path.join(class_path, file)
                img = Image.open(img_path)

                # Convert to RGB if needed
                if img.mode != "RGB":
                    img = img.convert("RGB")

                # Save as JPG
                new_name = os.path.splitext(file)[0] + ".jpg"
                img.save(os.path.join(converted_folder, new_name))

print("All .tif images converted to .jpg successfully!")

val_folder = "/content/dataset_split/val/NotThreats_jpg"

"""EVALUATION STEP **HIGH LOW MODEL EVALUATION**"""

from ultralytics import YOLO
import os

# Load trained model
model = YOLO("/content/runs/classify/baggage_classification/weights/best.pt")

# Correct test folders (where your images actually are)
test_folders = [
    "/content/dataset_split/train/HighLow_jpg",

]

for folder in test_folders:
    print(f"Testing images in folder: {folder}\n{'-'*50}")

    # Include only image files
    image_files = [os.path.join(folder, f)
                   for f in os.listdir(folder)
                   if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

    if not image_files:
        print("No images found!\n")
        continue

    for img_path in image_files:
        results = model(img_path)  # run prediction
        probs = results[0].probs   # get probabilities object

        pred_index = int(probs.top1)          # predicted class index
        confidence = float(probs.top1conf)    # confidence
        class_name = results[0].names[pred_index]  # class name

        print(f"Image: {os.path.basename(img_path)}")
        print(f"Predicted class: {class_name}, Confidence: {confidence:.2f}\n")

"""THREAT MODEL EVALUATION"""

from ultralytics import YOLO
import os

# Load trained model
model = YOLO("/content/runs/classify/baggage_classification/weights/best.pt")

# Correct test folders (where your images actually are)
test_folders = [
    "/content/dataset_split/train/ThreatsRGB",

]

for folder in test_folders:
    print(f"Testing images in folder: {folder}\n{'-'*50}")

    # Include only image files
    image_files = [os.path.join(folder, f)
                   for f in os.listdir(folder)
                   if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

    if not image_files:
        print("No images found!\n")
        continue

    for img_path in image_files:
        results = model(img_path)  # run prediction
        probs = results[0].probs   # get probabilities object

        pred_index = int(probs.top1)          # predicted class index
        confidence = float(probs.top1conf)    # confidence
        class_name = results[0].names[pred_index]  # class name

        print(f"Image: {os.path.basename(img_path)}")
        print(f"Predicted class: {class_name}, Confidence: {confidence:.2f}\n")

"""NON THREAT MODEL EVALUATION"""

from ultralytics import YOLO
import os

# Load trained model
model = YOLO("/content/runs/classify/baggage_classification/weights/best.pt")

# Correct test folders (where your images actually are)
test_folders = [
    "/content/dataset_split/val/NotThreats_jpg",

]

for folder in test_folders:
    print(f"Testing images in folder: {folder}\n{'-'*50}")

    # Include only image files
    image_files = [os.path.join(folder, f)
                   for f in os.listdir(folder)
                   if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

    if not image_files:
        print("No images found!\n")
        continue

    for img_path in image_files:
        results = model(img_path)  # run prediction
        probs = results[0].probs   # get probabilities object

        pred_index = int(probs.top1)          # predicted class index
        confidence = float(probs.top1conf)    # confidence
        class_name = results[0].names[pred_index]  # class name

        print(f"Image: {os.path.basename(img_path)}")
        print(f"Predicted class: {class_name}, Confidence: {confidence:.2f}\n")

"""EVALUATION"""

import os
from ultralytics import YOLO
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load your trained model (fine-tuned or original)
model = YOLO("/content/runs/classify/baggage_classification/weights/best.pt")  # adjust path

# Folders for evaluation (all classes)
eval_folders = {
    "NotThreats": "/content/dataset_split/train/HighLow_jpg",
    "HighLow": "/content/dataset_split/val/NotThreats_jpg",
    "ThreatsRGB": "/content/dataset_split/train/ThreatsRGB"
}

y_true = []
y_pred = []

# Loop through all folders & images
for class_name, folder_path in eval_folders.items():
    for filename in os.listdir(folder_path):
        if filename.lower().endswith(('.jpg', '.jpeg', '.png')):
            img_path = os.path.join(folder_path, filename)

            # Predict
            results = model(img_path)
            probs = results[0].probs
            pred_index = int(probs.top1)
            pred_label = results[0].names[pred_index]

            # Append true and predicted
            y_true.append(class_name)
            y_pred.append(pred_label)

# Compute metrics
accuracy = accuracy_score(y_true, y_pred)
print(f"\nOverall Accuracy: {accuracy:.4f}")

print("\nClassification Report:")
print(classification_report(y_true, y_pred, labels=["NotThreats", "HighLow", "ThreatsRGB"], digits=4))

cm = confusion_matrix(y_true, y_pred, labels=["NotThreats", "HighLow", "ThreatsRGB"])
print("\nConfusion Matrix:")
print(cm)

for i, (true_label, pred_label) in enumerate(zip(y_true, y_pred)):
    print(f"{i}: True={true_label}, Pred={pred_label}")

from ultralytics import YOLO

# Load your existing model
model = YOLO("/content/runs/classify/baggage_classification/weights/best.pt")

# Set hyperparameters for fine-tuning
# - Lower learning rate to avoid catastrophic forgetting
# - Increase epochs for better convergence
# - Apply class weights to help NotThreats
hyperparams = {
    "lr0": 0.0001,         # initial learning rate
    "epochs": 30,          # fine-tune for 30 epochs
    "batch": 16,           # adjust depending on your GPU memory
    "weight_decay": 0.0005
}

# Class weights (NotThreats heavier) - REMOVED as it's not a valid argument
# Example: NotThreats=2.0, HighLow=1.0, ThreatsRGB=1.0
# class_weights = [2.0, 1.0, 1.0]

# Train model with augmentation
model.train(
    data="/content/dataset_split",   # path to your dataset YAML or folder
    imgsz=224,
    batch=16,
    epochs=30,
    lr0=0.0001,
    optimizer="SGD",
    # class_weights=class_weights, # Removed invalid argument
    project="runs/classify/baggage_classification_finetune",
    name="NotThreats_finetuned",
    exist_ok=True
)

from ultralytics import YOLO
import os
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1️⃣ Load fine-tuned model
model = YOLO("/content/runs/classify/baggage_classification/weights/best.pt")

# 2️⃣ Define test folders with true labels
test_folders = {
    "NotThreats": "/content/dataset_split/val/NotThreats_jpg",
    "HighLow": "/content/dataset_split/val/HighLow_jpg",
    "ThreatsRGB": "/content/dataset_split/val/ThreatsRGB"
}

y_true = []
y_pred = []

# 3️⃣ Predict for all images
for true_label, folder in test_folders.items():
    for img_file in os.listdir(folder):
        if img_file.lower().endswith(('.jpg', '.jpeg', '.png')):
            img_path = os.path.join(folder, img_file)
            results = model(img_path)
            probs = results[0].probs
            pred_index = int(probs.top1)
            pred_class = results[0].names[pred_index]

            y_true.append(true_label)
            y_pred.append(pred_class)

# 4️⃣ Compute metrics
accuracy = accuracy_score(y_true, y_pred)
print(f"Overall Accuracy: {accuracy:.4f}\n")

print("Classification Report:")
print(classification_report(
    y_true, y_pred,
    labels=["NotThreats", "HighLow", "ThreatsRGB"],
    digits=4
))

print("Confusion Matrix:")
cm = confusion_matrix(y_true, y_pred, labels=["NotThreats", "HighLow", "ThreatsRGB"])
print(cm)

!pip install ultralytics fastapi uvicorn pyngrok pillow nest-asyncio

!pip install ultralytics gradio pillow

from ultralytics import YOLO
from PIL import Image
import gradio as gr

# Load your YOLO model
model = YOLO("/content/runs/classify/baggage_classification/weights/best.pt")  # replace with your trained model

def detect_image(img):
    results = model.predict(img, verbose=False)[0]
    annotated_img = results.plot()
    return annotated_img  # returns image with boxes

# Gradio interface
demo = gr.Interface(
    fn=detect_image,
    inputs=gr.Image(type="pil"),
    outputs=gr.Image(type="pil"),
    title="YOLO Threat Detection",
    description="Upload a baggage/CT scan image and see YOLO detections"
)

demo.launch()